common: &common
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000
  min_messages: warning

development:
  primary:
    <<: *common
    database: siteinspector_dev
    username: postgres
    password: postgres
    host: 172.18.0.3

test:
  primary:
    <<: *common
    database: siteinspector_test<%= ENV['TEST_ENV_NUMBER'] %>
    username: postgres
    password: postgres
    host: 172.18.0.3

production:
  primary:
    adapter: postgresql
    pool: 10
    url: <%= ENV["DATABASE_URL"] %>
